spring.application.name=TrainBookingApplication
server.port=8080
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/train_booking_db
spring.datasource.username=root
spring.datasource.password=Boss@8055
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.file.name=logs/myapp.log
logging.level.root=INFO
redis-cli --tls -u redis://default:gQAAAAAAAXIDAAIncDIzMmRiYjg4MTViNjE0ZmQ4YWY5MzFiNTY1ODdmMGY3NnAyOTQ3MjM@notable-pigeon-94723.upstash.io:6379